baseURL = "https://matejamaric.com/"
languageCode = "en"
title = "Mateja Marić's Homepage"
# Disable default taxonomies
disableKinds = ["taxonomy", "term"]
# Enable inline HTML
[markup.goldmark.renderer]
unsafe = true
